### ISSUE TITLE
Chpt2 - Adding a new item button is not functional

### ISSUE THREAD

**Issue by pgresl** [PacktPublishing/-Learn-WinUI-3.0#12]
Chpt2 - adding a new item button, calling async function to see MessageDialog is not working. Message window could be initialized 

private async void AddButton_Click(object sender, RoutedEventArgs e)
        {
            var dialog = new MessageDialog("Adding new item is not available yet.");
            **InitializeWithWindow.Initialize(dialog, WindowNative.GetWindowHandle(this));**
            await dialog.ShowAsync();
        }

Petr

**Comment by rajat-packt** [comment]
Hey @alvinashcraft, would it be possible for you to address this query of our reader?

**Comment by alvinashcraft** [comment]
Hi @pgresl. Most of this code was created for the now unsupported WinUI on UWP project type. According to the [docs](https://learn.microsoft.com/windows/apps/develop/ui-input/retrieve-hwnd#winui-3-with-c), the method used here should be getting the window handle `WinRT.Interop.WindowNative.GetWindowHandle(this)`.

The latest WinUI docs recommend using `ContentDialog` instead of `MessageDialog`. Check out the docs [here](https://learn.microsoft.com/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.controls.contentdialog) and try replacing the dialog type in your code.

**Comment by rajat-packt** [comment]
Thanks a lot for your valuable time and insight @alvinashcraft ! Appreciate it!

Hey @pgresl, I'll now be closing this issue, I hope this helped you.
